"""Adicionar tabela de e-mails enviados

Revision ID: deefa1bf4efd
Revises: 
Create Date: 2026-09-30 17:23:50.854626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deefa1bf4efd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails_sent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=128), nullable=False),
    sa.Column('recipient', sa.Text(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emails_sent')
    # ### end Alembic commands ###
